
language: android
jdk: openjdk8

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

notifications:
  email: false

before_install:
 - yes | sdkmanager "platforms;android-27"
 - chmod +x gradlew
 - mkdir "$ANDROID_HOME/licenses" || true
 - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
 - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script: ./gradlew clean build